GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJvcyIsImlhdCI6MTcwNjY0MjM0OSwiZXhwIjoxNzA2NjQyMzc5fQ.HIjTTHQnJSKU1D1BfPsOxJsrAhvq85N-APl57pp7d1U
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bros"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJvcyIsImlhdCI6MTcwNjY0MjMxNn0.dDzUcrlHHgGde_19t8WdclqTuTzGxtW9m8UBFN8wtU4"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJvcyIsImlhdCI6MTcwNjY0MjMxNn0.dDzUcrlHHgGde_19t8WdclqTuTzGxtW9m8UBFN8wtU4"
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username" : "Mario",
    "password": "one"
}

###
  
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "bros",
    "password": "one"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "username": "bros",
   "email": "bros@one.co",
   "password": "one"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "username": "Mario",
   "email": "one2@one.co",
   "password": "one"
}


### 
 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "username": "bross",
   "password": "something"
}

###

GET http://localhost:4000/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlvIiwiaWF0IjoxNzA4MjU0MjQ0LCJleHAiOjE3MDgyNTQ1NDR9.0F2wr1ZXlGPAh3FyHa6lZWUQrTIxmrO_LtV_qRwVMrE

###

GET http://localhost:3000/app/settings

###

GET http://localhost:3000/app/testing


###

GET http://localhost:3000/app/users


###
 
GET http://localhost:3000/app/users/Mario

###
 
GET http://localhost:3000/app/users/not-found

### 
 
PUT http://localhost:3000/app/users/bros
Content-Type: application/json

{
   "username": "mario2"

}

###
 
DELETE http://localhost:3000/app/users/Mario

###
 
GET http://localhost:3000/app/bugreports

###

POST http://localhost:3000/app/bugreports
Content-Type: application/json

  {
    "id": 1005,
    "title": "bug report 5",
    "priority": 3,
    "status": "New",
    "description": "lorem epsum...",
    "author": "jbravo",
    "created": "2024-02-13T14:26:11.000+00:00",
    "updated": "2024-05-14T11:11:12.000+00:00"
  }

###
 
GET http://localhost:3000/app/bugreports/1005

###

PUT http://localhost:3000/app/bugreports/1005
Content-Type: application/json

  {
    "title": "bug report 5 updated",
    "priority": 2,
    "status": "Fixed",
    "description": "lorem epsum... updated"
  }

###
 
DELETE http://localhost:3000/app/bugreports/1002